# -- Constants---
DATA_DIR = 'Datasets/processed/' 

#-- Hyperparams --
GENERATIONS = 1000
POPULATION_SIZE = 100
TOURNAMENT_PARTICIPANTS = 20
TOURNAMENT_SELECTION_PROB = 0.8
MUTATION_PROB = 0.5
ALPHA = 1.5
