# -- Constants---
DATA_DIR = 'Datasets/processed/' 

#-- Hyperparams --
GENERATIONS = 4000
POPULATION_SIZE = 100
TOURNAMENT_PARTICIPANTS = 20
TOURNAMENT_SELECTION_PROB = 0.8
MUTATION_PROB = 0.6
ALPHA = 1.6
