# -- Constants---
DATA_DIR = 'Datasets/processed/' 

#-- Hyperparams --
GENERATIONS = 2000
POPULATION_SIZE = 100
TOURNAMENT_PARTICIPANTS = 20
NUM_OF_MUTATED_GENES = 10
TOURNAMENT_SELECTION_PROB = 0.8
MUTATION_PROB = 0.08
CROSSOVER_PROB = 0.9
ALPHA = 1.2
